sonar.projectKey=ACEest-fitness-gym
sonar.projectName=ACEest Fitness Gym
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=venv/**,.venv/**,__pycache__/**,.pytest_cache/**,k8s/**,.github/**

sonar.python.version=3.11